/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#25006b",
        "on-secondary": "#004564",
        "surface-container-lowest": "#000000",
        "outline": "#65759e",
        "inverse-surface": "#faf8ff",
        "surface-dim": "#060e20",
        "inverse-on-surface": "#4d556b",
        "on-background": "#dee5ff",
        "secondary-container": "#00293e",
        "on-tertiary-container": "#620070",
        "surface-tint": "#a68cff",
        "on-secondary-fixed": "#004463",
        "on-primary-fixed": "#2d007f",
        "error-container": "#8a1632",
        "primary-container": "#7c4dff",
        "on-tertiary": "#710082",
        "secondary-fixed": "#c9e6ff",
        "primary-fixed-dim": "#bba6ff",
        "inverse-primary": "#6834eb",
        "primary-fixed": "#c8b7ff",
        "on-error": "#490013",
        "outline-variant": "#38476d",
        "surface-bright": "#172b54",
        "on-tertiary-fixed-variant": "#700081",
        "surface-container-high": "#101e3e",
        "secondary-dim": "#34b5fa",
        "background": "#060e20",
        "on-primary-container": "#ffffff",
        "surface-container": "#0c1934",
        "primary": "#a68cff",
        "primary-dim": "#7e51ff",
        "on-tertiary-fixed": "#3e0048",
        "secondary-fixed-dim": "#aadaff",
        "tertiary-fixed-dim": "#f27dff",
        "on-secondary-fixed-variant": "#00628c",
        "on-error-container": "#ff97a3",
        "on-surface": "#dee5ff",
        "on-primary-fixed-variant": "#4e00cd",
        "secondary": "#89ceff",
        "tertiary-container": "#f795ff",
        "on-secondary-container": "#27aef2",
        "error": "#fd6f85",
        "surface-variant": "#142449",
        "tertiary": "#fbabff",
        "surface-container-low": "#081329",
        "tertiary-dim": "#ec63ff",
        "surface-container-highest": "#142449",
        "error-dim": "#c8475d",
        "tertiary-fixed": "#f795ff",
        "on-surface-variant": "#9baad6",
        "surface": "#060e20",
        // Keeping legacy for safety until migration is complete
        'glass-bg': 'rgba(15, 17, 26, 0.7)',
        'glass-border': 'rgba(255, 255, 255, 0.1)',
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}
